#!/bin/bash
RETENTION_DAYS=${RETENTION_DAYS:-7}
PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "DELETE FROM payload_statuses WHERE created_at < (NOW() - interval '$RETENTION_DAYS days');"
PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "DELETE FROM payloads WHERE created_at < (NOW() - interval '$RETENTION_DAYS days');"
PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "VACUUM ANALYZE payload_statuses;"
PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "VACUUM ANALYZE payloads;"
PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "FOR table in SELECT * FROM partitions LOOP IF (table::INTEGER < (CAST((EXTRACT(DAY from NOW()) + (100 * EXTRACT(MONTH from NOW())) + (10000 * EXTRACT(YEAR from NOW()))) AS INTEGER) - $RETENTION_DAYS) THEN DROP TABLE table; END IF; END LOOP;"