version: '3'
services:
  payload-tracker-db:
    image: registry.redhat.io/rhel8/postgresql-12
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=payloadtracker
      - POSTGRESQL_USER=payloadtracker
      - POSTGRESQL_PASSWORD=payloadtracker
    command: sh -c "mkdir -p /opt/app-root/src/postgresql-start &&
                    echo 'psql -c \"ALTER USER payloadtracker CREATEDB;\"' >> /opt/app-root/src/postgresql-start/make_test_work.sh &&
                    run-postgresql"
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_BROKER_ID=1
      - KAFKA_NUM_PARTITIONS=4
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
  redis:
    image: registry.redhat.io/rhel8/redis-5
    ports:
      - 6379:6379
    depends_on:
      - payload-tracker-db
    environment:
      - REDIS_PASSWORD=payloadtracker
