{
 "title": "Payload Tracker",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Payload Tracker Up",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=\"payload-tracker\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API Responses",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_api_response_count_total[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "API Reponse Counts",
   "type": "stat",
   "description": "Uses time range interval to find average",
   "gridPos": { "h": 12, "w": 6, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg_over_time(payload_tracker_api_response_count_total[$__interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pod Up (98%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"payload-tracker\"}[24h]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Successfully Processed Messages (95%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_msg_count_total{status=\"success\"}[$__range])) / sum(increase(payload_tracker_msg_count_total{status=\"consumed\"}[$__range])) * 100"
    }
   ]
  },
  {
   "title": "Percentage of non-5xx (95%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(payload_tracker_api_response_count_total{status!~\"5.*\"}[$__interval])) / sum(sum_over_time(payload_tracker_api_response_count_total[$__interval]))"
    }
   ]
  },
  {
   "title": "Service Status Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(payload_tracker_service_status_counter_total[1m])) by (service_name, status, source_name)",
     "legendFormat": "{{service_name}} (source: {{source_name}}) - {{status}}"
    }
   ]
  },
  {
   "title": "Platform Upload Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(payload_tracker_upload_time_elapsed_sum[1m]) / rate(payload_tracker_upload_time_elapsed_count[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(payload_tracker_upload_time_by_service_elapsed_sum[1m]) / rate(payload_tracker_upload_time_by_service_elapsed_count[1m])) by (service_name, source_name)",
     "legendFormat": "{{service_name}} (source: {{source_name}})"
    }
   ]
  }
 ]
}